# Generated by Django 3.0.7 on 2020-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okved2', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpd2', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('post_index', models.CharField(blank=True, max_length=64, null=True)),
                ('activities', models.ManyToManyField(to='attemption1.Activity')),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
    ]
