# Generated by Django 3.0.7 on 2020-06-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attemption1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='actions',
            new_name='activities',
        ),
    ]
