# Generated by Django 3.0.7 on 2020-06-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200607_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True, 'verbose_name': 'Вид деятельности', 'verbose_name_plural': 'Виды деятельности'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='activities',
        ),
        migrations.DeleteModel(
            name='CompanyActivities',
        ),
    ]
