# Generated by Django 3.0.7 on 2020-06-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200607_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activities',
            field=models.ManyToManyField(related_name='companies', to='main.Activity'),
        ),
    ]
