# Generated by Django 3.0.7 on 2020-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_company_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='okved2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ОКВЭД2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='activities',
            field=models.ManyToManyField(null=True, related_name='companies', to='main.Activity'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='post_index',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Почтовый индех'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='okpd2',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ОКПД2'),
        ),
    ]
