# Generated by Django 3.0.7 on 2020-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200608_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='post_index',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Короткое название'),
        ),
    ]
