# Generated by Django 3.0.7 on 2020-06-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200608_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='company',
            name='list_org_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='companies', to='main.Activity'),
        ),
    ]
