# Generated by Django 3.0.7 on 2020-06-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200609_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='list_org_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на list-org.com'),
        ),
    ]
