# Generated by Django 3.0.7 on 2020-06-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_company_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Activity'),
        ),
    ]
