# Generated by Django 3.0.7 on 2020-06-16 14:20

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_company_main_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='Почтовый индех')),
                ('federal_subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='Субъект федерации')),
                ('locality', models.CharField(blank=True, max_length=128, null=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, max_length=256, null=True, verbose_name='Улица')),
                ('remain', models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер дома, квартиры, строения и т.п.')),
                ('gps_coordinates', models.CharField(blank=True, max_length=32, null=True, verbose_name='GPS координаты')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='site',
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField(blank=True, help_text='Сайт', verbose_name='Сайт')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Company')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'db_table': 'site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Номер телефона', max_length=31, verbose_name='Телефон')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Company')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'db_table': 'phone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', phone_field.models.PhoneField(blank=True, help_text='Номер факса', max_length=31, verbose_name='Факс')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Company')),
            ],
            options={
                'verbose_name': 'Факс',
                'verbose_name_plural': 'Факсы',
                'db_table': 'fax',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='E-mail', max_length=254, verbose_name='E-mail')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Company')),
            ],
            options={
                'verbose_name': 'E-mail',
                'db_table': 'email',
                'managed': True,
            },
        ),
    ]
