# Generated by Django 3.0.7 on 2020-06-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200616_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okved',
            name='okved2',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ОКВЭД2'),
        ),
    ]
