# Generated by Django 3.0.8 on 2020-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200616_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='okopf',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКОПФ'),
        ),
    ]
