# Generated by Django 3.1 on 2020-08-16 16:26

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Короткое название')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=32, null=True, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКПО')),
                ('ogrn', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОГРН')),
                ('okfs', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКФС')),
                ('okopf', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКОПФ')),
                ('oktmo', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКТМО')),
                ('okato', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКАТО')),
                ('okogu', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОКОГУ')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('is_active', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'URL организации',
                'db_table': 'organization_url',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField(blank=True, help_text='Сайт', verbose_name='Сайт')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='list_org_parser.organization')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'db_table': 'site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Номер телефона', max_length=31, verbose_name='Телефон')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='list_org_parser.organization')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'db_table': 'phone',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='list_org_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='list_org_parser.organizationurl'),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_okved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classifiers.okved2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sup_okveds',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='classifiers.Okved2'),
        ),
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', phone_field.models.PhoneField(blank=True, help_text='Номер факса', max_length=31, verbose_name='Факс')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='list_org_parser.organization')),
            ],
            options={
                'verbose_name': 'Факс',
                'verbose_name_plural': 'Факсы',
                'db_table': 'fax',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='E-mail', max_length=254, verbose_name='E-mail')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='list_org_parser.organization')),
            ],
            options={
                'verbose_name': 'E-mail',
                'db_table': 'email',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024, verbose_name='Адрес')),
                ('is_legal', models.BooleanField(blank=True, default=False, verbose_name='Юридический')),
                ('gps_longitude', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Долгота')),
                ('gps_latitude', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Широта')),
                ('comment', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='list_org_parser.organization')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
                'managed': True,
            },
        ),
    ]
