# Generated by Django 3.1 on 2020-08-16 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_okved2007'),
        ('list_org_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='main_okved',
            new_name='main_okved2',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='sup_okveds',
            new_name='sup_okveds2',
        ),
        migrations.AddField(
            model_name='organization',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_okved2007',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classifiers.okved2007'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sup_okveds2007',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='classifiers.Okved2007'),
        ),
    ]
