# Generated by Django 3.1 on 2020-08-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_org_parser', '0002_auto_20200816_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
